#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:
  typeAliasesPackage: com.tmxk.lifeschedule.goal.model
#  mapperLocations: classpath:*.xml
  mapperLocations: classpath:com/tmxk/lifeschedule/goal/mapper/*.xml

---

#开发配置:
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/lifeschedule?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8080